### PR TITLE
Automatically commit blacklisted ports

### LINKED ISSUE #4: `InputStore`: store module and PRs to blacklist in one file per module
### Context
Currently all these data are stored in one file, but the goal would be to store these information in the Git repository to share them with other contributors (if we decide to blacklist a PR or to not port an addon to a version, we don't want to be annoyed with this anymore).

### TODO

To ease this sharing, better to avoid conflicts on one global file and improve the readability by splitting it with one file per module. Knowing that this file will be stored on the source branch:
```js
# File '.oca-port/blacklist/shopfloor.json' on 14.0 branch
{
    "pull_requests": {
        "13.0": [
            299    # Do not port PR #299 from 14.0 to 13.0
        ],
        "15.0": [
            312    # Do not port PR #312 from 14.0 to 15.0
        ]
    },
    "no_migration": {
        "12.0": true    # Do not migrate this module from 14.0 to 12.0
    }
}
```
Maybe the `no_migration` key should be stored in the target branch, to indicate we don't want this module on this version, without taking into account the source branch:
```js
# File .oca-port/blacklist/'shopfloor.json' on X.Y branch
{
    "no_migration": true    # Do not migrate this module on this version
}
```
:thinking:

### PR DESCRIPTION
**Pull request by sebalix**
This change is not backward-compatible.

This feature will store blacklisted PR or module migration in a `./oca-port/blacklist/{MODULE}.json` file (one file per module) and this will be committed in the working branch so this information will be shared with other contributors (PR or module blacklisted won't be listed anymore, but the reason why it was blacklisted will be displayed instead).

Here is a demo of a blacklisted PR with the current changes: https://github.com/OCA/wms/pull/464
image

fix #4

### CODE REVIEW

**Comment by sebalix** [comment]
I wonder if we should add a comment when we blacklist something, explaining the reason why we did it (changes already ported, lint, doesn't apply anymore, module replaced by another one or renamed...)

**Review by ivantodorovich — COMMENTED** [review]
I suggest to store this file in `.oca/oca-port/blacklist/{MODULE}.json` (or similar)
Goal is to put it under an `.oca` directory that we can use for (possible) future oca tools

Also maybe use a `yml` file instead of `json`, that's more common than json in this kind of tools

**Comment by sebalix** [comment]
@ivantodorovich good ideas. For YAML the only drawback is to introduce a new dependency, while JSON is part of the Python std lib.

**Comment by simahawk** [comment]
I agree on the path, I agree on keeping JSON. And, yes, let's collect a comment!

**Comment by sebalix** [comment]
@simahawk I'll try to pop-up the editor during the `git commit`, or add a user input in the commit message. I don't think we need to store this in the JSON file.

**Comment by sebalix** [comment]
Here is a demo of a blacklisted PR with the current changes: https://github.com/OCA/wms/pull/464

**Comment by sebalix** [comment]
I'm quite happy with these changes at the moment, and want to build a new release for that, so... merging :)

**Pull request merged**
